global:
  scrape_interval:     10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'author-api'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['author-api:8082']
        labels:
          application: 'Author Service Application'